# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30ce8049016472dcff0c01a1ed14af962caac4305888ae1d223f633bdca19cd1f74749e23e6d988d2f51c48cb2a7cc4abef160c6860c84e580473f8adde161f6

test:
  secret_key_base: f7be10ae77d64547a42f0f999e2d579ddf9dec0278515660cd09edc3e979e6db66ccb2c715fcd64d51c3c823d815d64c83130f833eca7f4669b389bc2d2f1714

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
